apiVersion: v1
kind: Pod
metadata:
  name: kubectl
spec:
  containers:
  - name: jnlp
    image: jenkins/jnlp-slave:3.35-5-alpine
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
  - name: kubectl
    image: bitnami/kubectl:1.15
    command:
    - bash
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
  restartPolicy: Never
